services:
  - type: web
    name: emotion-api
    env: python
    buildCommand: |
      echo "python-3.10.13" > runtime.txt
      pip install -r requirements.txt
    startCommand: gunicorn emotion_api:app
